### PR TITLE
Use Minimal mistakes theme

### PR DESCRIPTION
**Pull request by gmitch215**
Details in #2 

Changed to branch for CF Preview Deployment.

### CODE REVIEW

**Comment by Andre601** [comment]
The only thing that seems to be left to address is the number of items per row. By the looks of it is the theme using `display: table` for this and I'm not sure where or how I could adjust the display to fit 4 items here... Open for ideas.

**Comment by gmitch215** [comment]
If you can override the display type (e.g. `display: flex !important;`), then you can use flexbox to change the column count, or use the `column-count` property (unsupported on tables).

If not, you could try wrapping the icons in a `<tr>` tag since that would force them all into a single row, but I'm not sure if you can edit the HTML directly.

**Comment by Andre601** [comment]
Implemented a solution that makes the columns span 4 columns using flex display, except when screen size becomes to small at which point it defaults back to table display.

**Comment by gmitch215** [comment]
Looks nice. Only other thing I would say is the duplicate title `"CodeMC - CodeMC"`, not sure if that's intentional or some kind of framework bug.

**Comment by Andre601** [comment]
Adjusted the title to now have `Welcome to CodeMC - CodeMC`

The `- CodeMC` comes from the title defined in `_config.yml` which is needed for the navbar header from what I can tell, so we can't really get rid of it without editing the entire template itself I guess (Unless custom header allows to override the title attribute).

**Comment by Andre601** [comment]
Actually managed to override the title attribute by simply copying the `_includes/seo.html` file and change the `<title>...</title>` part to just use `CodeMC`.

**Review by Andre601 — APPROVED** [review]

**Comment by gmitch215** [comment]
Cool.

Last thing I would say is to maybe add logos to the resources section (Jenkins, Nexus, GitHub logos) similar to how we have it for Authors.

**Comment by Andre601** [comment]
> Cool.
> 
> Last thing I would say is to maybe add logos to the resources section (Jenkins, Nexus, GitHub logos) similar to how we have it for Authors.

Okay. I personally would go with (SVG) icons, but would also be fine with normal images for as long as we are allowed to use them freely (As in not having to deal with licenses or copyright).

**Comment by Andre601** [comment]
Added logos to the resources section by getting SVG files where possible (in case of sonatype did I had to obtain a ESP one), resize them to a consistent 256x256 and made them mono colored (white) for consistency.

I also added a LICENSE.txt to the image folder informing about the sources and copyrights of the images (Jenkins seems to be CC by-sa 3.0 from what I could gather. It's not quite clear unfortunately, hence why I added a disclaimer regarding the accuracy of the info).

**Comment by gmitch215** [comment]
Looks perfect.

**Comment by Andre601** [comment]
Decided to also add images for Discord and documentation for the sake of consistency.

**Comment by Andre601** [comment]
I would consider this PR completed from my end.

**Comment by gmitch215** [comment]
Sounds good.

**Pull request merged**
